# Generated by Django 4.1.7 on 2023-03-08 12:03

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=portfolio.models.get_default_created_at),
        ),
    ]
