# Generated by Django 4.1.7 on 2023-03-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_skills', to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill'),
        ),
    ]
