# Generated by Django 4.1.7 on 2023-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_skill_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='portfolio.skill'),
        ),
    ]
